// @version=5
// created by mthuong

indicator(title="EMA 34-89 / Ichimoku Cloud", shorttitle="EMA Ichimoku", overlay=true)
conversionPeriods = input.int(9, minval=1, title="Conversion Line Length")
basePeriods = input.int(26, minval=1, title="Base Line Length")
laggingSpan2Periods = input.int(52, minval=1, title="Leading Span B Length")
displacement = input.int(26, minval=1, title="Lagging Span")
donchian(len) => math.avg(ta.lowest(len), ta.highest(len))
conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = math.avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)
plot(conversionLine, color=#2962FF, title="Conversion Line")
plot(baseLine, color=#B71C1C, title="Base Line")
plot(close, offset = -displacement + 1, color=#43A047, title="Lagging Span")
p1 = plot(leadLine1, offset = displacement - 1, color=#A5D6A7,
	 title="Leading Span A")
p2 = plot(leadLine2, offset = displacement - 1, color=#EF9A9A,
	 title="Leading Span B")
plot(leadLine1 > leadLine2 ? leadLine1 : leadLine2, offset = displacement - 1, title = "Kumo Cloud Upper Line", display = display.none) 
plot(leadLine1 < leadLine2 ? leadLine1 : leadLine2, offset = displacement - 1, title = "Kumo Cloud Lower Line", display = display.none) 
fill(p1, p2, color = leadLine1 > leadLine2 ? color.rgb(67, 160, 71, 90) : color.rgb(244, 67, 54, 90))

// EMA 34

len1=input.int(34, title="EMA 34-low")
len2=input.int(34, title="EMA 34-close")
len3=input.int(34, title="EMA 34-high")
len4=input.int(89, title="EMA 89-close")
len5=input.int(200, title="EMA 200-close")
len6=input.int(400, title="EMA 400-close")

M1=ta.ema(low, len1)
M2=ta.ema(close, len2)
M3=ta.ema(high, len3)
M4=ta.ema(close, len4)
M5=ta.ema(close, len5)
M6=ta.ema(close, len6)

plot(M1, color=#9C28B0, linewidth=1, title="EMA 34-low")
plot(M2, color=#9C28B0, linewidth=1, title="EMA 34-close")
plot(M3, color=#9C28B0, linewidth=1, title="EMA 34-high")
plot(M4, color=#FFEE58, linewidth=2, title="EMA 89-close")
plot(M5, color=#00BCD4, linewidth=2, title="EMA 200-close")
plot(M6, color=#009688, linewidth=2, title="EMA 400-close")
